### ISSUE TITLE
set up travis ci

### ISSUE THREAD

**Issue by zeroual** [FaustXVI/junit5-docker#1]
can i  link your project to travis ci ?

**Comment by FaustXVI** [comment]
Sure :D

**Comment by vdemeester** [comment]
@zeroual you need to configure the `travis.yml`, @FaustXVI will enable/link it.
To try out your travis setup, link your for to it.

**Comment by zeroual** [comment]
yeah @vdemeester  , I just do it , i think it's work 
[https://travis-ci.org/zeroual/junit5-docker/builds/149697671](url)
i have the same fail in my local machine

**Comment by FaustXVI** [comment]
fixed by pr #2
