### ISSUE TITLE
Wait for container to be ready

### ISSUE THREAD

**Issue by FaustXVI** [FaustXVI/junit5-docker#3]
Currently, the test is run as soon as we send a request to the docker deamon. The container may not be ready at the time we run the tests.
We can wait for it two ways : 
* [x] wait for something to appear in the logs (see #4)
* [x] ~~since docker 1.12 use the health-check system~~

**Comment by vdemeester** [comment]
Updated

**Comment by FaustXVI** [comment]
Docker's health-check feature has been moved to #12

**Comment by vdemeester** [comment]
@FaustXVI ok so you should update the description of #4 to add "Closes #3" :angel:
