### ISSUE TITLE
Build on Windows, OSx and Linux

### ISSUE THREAD

**Issue by FaustXVI** [FaustXVI/junit5-docker#66]
We can add appveyor for windows and travis for osx

**Comment by zeroual** [comment]
for the moment i wil run all tests in my mac and windows

**Comment by FaustXVI** [comment]
Well, for now, nor appveyor nor travis for osx support nested virtualization so we can't have docker for windows nor docker for mac. :(
The other way to do it is to have a dedicated CI on windows and another on osx but we don't have that for now :S
I'll leave the issue open but will remove the milestone

**Comment by FaustXVI** [comment]
We should go as far as possible with that. Trying to build it without ITs seem to be a fair goal.
