### ISSUE TITLE
Why not TestContainers?

### ISSUE THREAD

**Issue by bsideup** [FaustXVI/junit5-docker#91]
Hi there,

I'm wondering if there is something you miss in http://github.com/testcontainers/testcontainers-java so you decided to start this project? :) Or you just didn't know probably?

Maybe we can join our efforts?

**Comment by FaustXVI** [comment]
Hi @bsideup 

To be honest, this project started as an exercise to explore JUnit5 extensions.
I did noticed testContainers but my goal wasn't to build up a new solution, just to train me :)

I totally agree to join our efforts. I think a first step could be to use testContainers as my api gateway and if that's successful, maybe join the projects ?

**Comment by bsideup** [comment]
@FaustXVI happy to hear that :)

TestContainers is an organization on GitHub, so everyone can contribute and even become a committer (this is what we (ZeroTurnaround) did), so it totally makes sense to join them :) 

We did the same 1 year ago actually, instead of developing our own testing engine we just contributed our all wishes to TestContainers and continued the development as a part of it :)

**Comment by bsideup** [comment]
@FaustXVI FYI we have a Slack channel to discuss stuff:
http://slack.testcontainers.org
