### ISSUE TITLE
Compatibility issues with JUnit 5.0.0-RC2

### ISSUE THREAD

**Issue by robert-malai** [FaustXVI/junit5-docker#98]
Because of the new life cycle model, there are no more ContainerExtensionContext or TestExtensionContext in the org.junit.jupiter.api.extension package.

Due to this, the containers are failing to start before the tests.

**Comment by FaustXVI** [comment]
Thanks for letting us know 😄 
We'll fix that as soon as possible and include it in the next release candidate.

**Comment by vdemeester** [comment]
@robert-malai fixed 🎉 (and pushed to maven central, RC5)
